spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://192.168.56.1:3306/users
#    username: users
#    password: 1234
    url: jdbc:mariadb://localhost:3306/users
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true    
